<a href="https://colab.research.google.com/github/harika373/10I7-Batch21/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [76, 88, 69],
    [90, 91, 85],
    ])
print("Student Marks:\n",marks)


Student Marks:
 [[85 78 92]
 [76 88 69]
 [90 91 85]]


In [2]:
avg_stu=np.mean(marks, axis=1)
print("\nAverage marks per student:",avg_stu)

min_stu=np.min(marks, axis=0)
print("\nMinimum marks per student:",min_stu)

max_stu=np.max(marks, axis=0)
print("\nMaximum marks per student:",max_stu)



Average marks per student: [85.         77.66666667 88.66666667]

Minimum marks per student: [76 78 69]

Maximum marks per student: [90 91 92]


In [3]:
print("Marks of student 1:",marks[0])

print("Marks of first 3 students :\n",marks[:3])

Marks of student 1: [85 78 92]
Marks of first 3 students :
 [[85 78 92]
 [76 88 69]
 [90 91 85]]


In [4]:
high_achievers = marks[np.all(marks > 80, axis=1)]
print("\nStudents scoring above 80 in all subjects:\n", high_achievers)


Students scoring above 80 in all subjects:
 [[90 91 85]]


In [5]:
subject_wise = marks.T
print("\nSubject-wise performance:\n", subject_wise)



Subject-wise performance:
 [[85 76 90]
 [78 88 91]
 [92 69 85]]


In [6]:
print("1.Student 3 has scored consistently high.")
print("2.Subject 3 has the highest average performance")
print("3.1 student(s) scored above 80 in all subjects.")

1.Student 3 has scored consistently high.
2.Subject 3 has the highest average performance
3.1 student(s) scored above 80 in all subjects.
