<a href="https://colab.research.google.com/github/harika373/10I7-Batch21/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#1st Assessment

In [7]:
import numpy as np

In [2]:
# Generate a 2D array of shape (4x4) with random test scores (between 40 and 100)
scores = np.random.randint(40, 101, size=(4, 4))
print("Test Scores (4x4 matrix):\n", scores)


Test Scores (4x4 matrix):
 [[88 97 59 61]
 [49 67 63 88]
 [96 57 45 61]
 [67 67 77 93]]


In [3]:
# Row-wise and Column-wise means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)



Row-wise Means: [76.25 66.75 64.75 76.  ]
Column-wise Means: [75.   72.   61.   75.75]


In [4]:
# Standard Deviation and Variance
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)


Standard Deviation: 16.222934190521762
Variance: 263.18359375


In [5]:
# Global Max, Min and their Indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("\nGlobal Maximum:", global_max, "at index", max_index)
print("Global Minimum:", global_min, "at index", min_index)



Global Maximum: 97 at index (np.int64(0), np.int64(1))
Global Minimum: 45 at index (np.int64(2), np.int64(2))


In [6]:
# Median values (row & column-wise)
row_medians = np.median(scores, axis=1)
col_medians = np.median(scores, axis=0)
print("\nRow-wise Medians:", row_medians)
print("Column-wise Medians:", col_medians)


Row-wise Medians: [74.5 65.  59.  72. ]
Column-wise Medians: [77.5 67.  61.  74.5]


In [10]:
# 2nd Assignment

In [11]:
import numpy as np

In [12]:
# Create a 3x3x3 RGB image with pixel values (0–255)
image = np.random.randint(0, 256, size=(3, 3, 3), dtype=np.uint8)
print("Original Image (3x3x3 RGB matrix):\n", image)

Original Image (3x3x3 RGB matrix):
 [[[197 153 164]
  [ 30 133 153]
  [201 249  22]]

 [[ 60 255 238]
  [204  60  99]
  [200 255 122]]

 [[ 30  78 186]
  [105 193 228]
  [ 71  79 193]]]


In [13]:
# Extract Red, Green, Blue channels using slicing
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]

print("\nRed Channel:\n", red_channel)
print("\nGreen Channel:\n", green_channel)
print("\nBlue Channel:\n", blue_channel)



Red Channel:
 [[197  30 201]
 [ 60 204 200]
 [ 30 105  71]]

Green Channel:
 [[153 133 249]
 [255  60 255]
 [ 78 193  79]]

Blue Channel:
 [[164 153  22]
 [238  99 122]
 [186 228 193]]


In [15]:
# Compute average intensity per channel
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)

print("\nAverage Intensities -> Red:", avg_red,
      "Green:", avg_green,
      "Blue:", avg_blue)



Average Intensities -> Red: 122.0 Green: 161.66666666666666 Blue: 156.11111111111111


In [16]:
# Brighten the image by adding a scalar (clip at 255)
brightened_image = np.clip(image + 50, 0, 255)
print("\nBrightened Image:\n", brightened_image)


Brightened Image:
 [[[247 203 214]
  [ 80 183 203]
  [251  43  72]]

 [[110  49  32]
  [254 110 149]
  [250  49 172]]

 [[ 80 128 236]
  [155 243  22]
  [121 129 243]]]


In [17]:
# Compare before and after for brightness change
print("\nBefore Brightness Change (Pixel [0,0]):", image[0, 0])
print("After Brightness Change (Pixel [0,0]):", brightened_image[0, 0])


Before Brightness Change (Pixel [0,0]): [197 153 164]
After Brightness Change (Pixel [0,0]): [247 203 214]
