<a href="https://colab.research.google.com/github/harika373/10I7-Batch21/blob/main/numpy-Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
#1D Array
arr=np.array([1,2,3,4])
print("1D Array:",arr)

1D Array: [1 2 3 4]


In [7]:
#2D Array
arr=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [8]:
#Zeros Array
arr=np.zeros((3,3))
print("Zeros Array:\n",arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#one Array
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#range of numbers
range_arr=np.arange(0,10,2)
print("Range Array:\n",range_arr)

Range Array:
 [0 2 4 6 8]


In [11]:
#Random Array
rand_arr=np.random.rand(3,3)
print("Random Array:\n",rand_arr)

Random Array:
 [[0.97826997 0.68192841 0.13568497]
 [0.05696838 0.83393851 0.13166907]
 [0.22753483 0.02270937 0.18266475]]


In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print("Original Array:\n",arr)
print("shape:",arr.shape)
print("Data Types: ",arr.dtype)
print("Size:",arr.size)
print("item Size:",arr.itemsize)


Original Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Data Types:  int64
Size: 6
item Size: 8


In [17]:
arr=np.array([10,20,30,40,50])
print("first element",arr[0])
print("last element",arr[-1])
print("Slice[1:4]:",arr[1:4])
print("Every Second element",arr[::2])

first element 10
last element 50
Slice[1:4]: [20 30 40]
Every Second element [10 30 50]


In [20]:
arr=np.array([[1,2,3],[4,5,6]])
print("Element at (0,1):",arr[0,1])
print("Second row",arr[1,:])
print("Second Coloumn:",arr[:,1])

Element at (0,1): 2
Second row [4 5 6]
Second Coloumn: [2 5]


In [21]:
#Array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [24]:
#Mathemtcal Functions
arr=np.array([1,2,3,4,5,6])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Sin:",np.sin(arr))
print("Cos:",np.cos(arr))
print("Tan:",np.tan(arr))
print("Log:",np.log([1,np.e,np.e**2]))
print("Exp:",np.exp([1,2]))
print("sqrt:",np.sqrt([1,4,9]))
print("sort:",np.sort(arr))
print("argsort:",np.argsort(arr))
print("argmax:",np.argmax(arr))
print("argmin:",np.argmin(arr))
print("std:",np.std(arr))
print("var:",np.var(arr))
print("cumsum:",np.cumsum(arr))
print("cumprod:",np.cumprod(arr))
print("unique:",np.unique(arr))

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
Tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
Log: [0. 1. 2.]
Exp: [2.71828183 7.3890561 ]
sqrt: [1. 2. 3.]
sort: [1 2 3 4 5 6]
argsort: [0 1 2 3 4 5]
argmax: 5
argmin: 0
std: 1.707825127659933
var: 2.9166666666666665
cumsum: [ 1  3  6 10 15 21]
cumprod: [  1   2   6  24 120 720]
unique: [1 2 3 4 5 6]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
print("Original Array:\n",arr)
print("Reshape Array:\n",arr.reshape(3,2))
print("Transpose Array:\n",arr.T)
print("Flatten Array:\n",arr.flatten())
print("sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("std:",np.std(arr))
print("var:",np.var(arr))
print("cumsum:",np.cumsum(arr))
print("sum along axis 0",np.sum(arr,axis=0))
print("sum along axis 1",np.sum(arr,axis=1))


Original Array:
 [[1 2 3]
 [4 5 6]]
Reshape Array:
 [[1 2]
 [3 4]
 [5 6]]
Transpose Array:
 [[1 4]
 [2 5]
 [3 6]]
Flatten Array:
 [1 2 3 4 5 6]
sum: 21
mean: 3.5
min: 1
max: 6
std: 1.707825127659933
var: 2.9166666666666665
cumsum: [ 1  3  6 10 15 21]
sum along axis 0 [5 7 9]
sum along axis 1 [ 6 15]


In [28]:
#Brodcasting
a=np.array([1,2,3])
b=5
c=np.array([[4],[5],[6]])
d=np.array([7,8,9])
print("a:\n",a)
print("b:\n",b)
print("a+b:\n",a+b)
print("c:\n",c)
print("d:\n",d)
print("c+d:\n",c+d)

a:
 [1 2 3]
b:
 5
a+b:
 [6 7 8]
c:
 [[4]
 [5]
 [6]]
d:
 [7 8 9]
c+d:
 [[11 12 13]
 [12 13 14]
 [13 14 15]]


In [30]:
#matrics operations
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("A:\n",A)
print("B:\n",B)
print("A+B:\n",A+B)
print("A-B:\n",A-B)
print("A*B:\n",A*B)
print("A/B:\n",A/B)
print("A.dot(B):\n",A.dot(B))
print("np.dot(A,B):\n",np.dot(A,B))
print("inverse:\n",np.linalg.inv(A))
print("determinant:\n",np.linalg.det(A))
print("rank:\n",np.linalg.matrix_rank(A))
print("trace:\n",np.trace(A))
print("eigenvalues:\n",np.linalg.eigvals(A))
print("eigenvectors:\n",np.linalg.eig)
print("Transpose\n",A.T)

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
A+B:
 [[ 6  8]
 [10 12]]
A-B:
 [[-4 -4]
 [-4 -4]]
A*B:
 [[ 5 12]
 [21 32]]
A/B:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
A.dot(B):
 [[19 22]
 [43 50]]
np.dot(A,B):
 [[19 22]
 [43 50]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant:
 -2.0000000000000004
rank:
 2
trace:
 5
eigenvalues:
 [-0.37228132  5.37228132]
eigenvectors:
 <function eig at 0x784e66f62520>
Transpose
 [[1 3]
 [2 4]]


In [31]:
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]


In [32]:
# Generate random marks (between 50 and 100) for 5 students in 4 subjects
marks = np.random.randint(50, 101, size=(5, 4))
print("Marks of students:\n", marks)

# Average marks per student
avg_per_student = np.mean(marks, axis=1)
print("\nAverage marks per student:", avg_per_student)

# Average marks per subject
avg_per_subject = np.mean(marks, axis=0)
print("Average marks per subject:", avg_per_subject)

# Student with the highest total marks
total_per_student = np.sum(marks, axis=1)
top_student = np.argmax(total_per_student) + 1  # +1 for student numbering
print("Student with highest total marks: Student", top_student)

# Subject with the lowest average score
lowest_subject = np.argmin(avg_per_subject) + 1
print("Subject with lowest average score: Subject", lowest_subject)


Marks of students:
 [[63 60 53 86]
 [79 98 81 50]
 [96 71 83 53]
 [67 99 70 94]
 [61 65 78 69]]

Average marks per student: [65.5  77.   75.75 82.5  68.25]
Average marks per subject: [73.2 78.6 73.  70.4]
Student with highest total marks: Student 4
Subject with lowest average score: Subject 4
